### ISSUE TITLE
Jms deserializer class with parent properties

### ISSUE THREAD

**Issue by shubaivan** [schmittjoh/JMSSerializerBundle#774] opened 2019-10-30 09:39 UTC
I use `"jms/serializer": "^3.3",` stand alone. And my goal create parent class for two child with common properties. I did it. Cretae parent class `Request` and two child - `ApiRequest` and `FormRequest`. Child differ in that they have different serializer names for properties that's all. I use yml mapping. 

    /**
     * Class Request
     */

    class Request
    {
    /**
     * @var SignatureType
     * @Assert\NotBlank()
     */
    public $signatureType;

Child

    /**
     * Class ApiRequest
     * @package CDB\Collection\DTO
     * @RequestApplication()
     * @SignatoryTypeConstraint()
     */
    class ApiRequest extends Request
    {
    
    }
    
and child config `CDB.Collection.DTO.ApiRequest.yml`

    CDB\Collection\DTO\ApiRequest:
      exclusion_policy: ALL
      properties:
        signatureType:
          expose: true
          type: string
          serialized_name: signatureType

For parent I don't have config

and when I try deserialize json 

    {
     
        "signatureType": "bankid"
    }

Object have empty property

When I try deserializer json 

    {
     
        "signature_type": "bankid"
    }

I determined that metadata for child class did not contain `propertyMetadata. When I remove condtiion in 

`jms/serializer/src/Metadata/Driver/YamlDriver.php`

from 

```
            foreach ($class->getProperties() as $property) {
                if ($property->class !== $name || (isset($property->info) && $property->info['class'] !== $name)) {
                    continue;
                }
```

to 

```
            foreach ($class->getProperties() as $property) {
                if ((isset($property->info) && $property->info['class'] !== $name) {
                    continue;
                }
```

`$metadata` for my class metadata began to contain data about my child class. Because `$class->getProperties()` reflection function which get properties from parent, that's why property class name and class for which metadata generated is different. 
Maybe I select wrong way or who know how to correct work with yml configuration for class whose properties from parent classes ?

**Comment by shubaivan** [comment] 2019-10-30 11:56
when I remove condtiion in 
`repositories/cdb.preem.se/vendor/jms/serializer/src/Metadata/Driver/YamlDriver.php`
from 

```
            foreach ($class->getProperties() as $property) {
                if ($property->class !== $name || (isset($property->info) && $property->info['class'] !== $name)) {
                    continue;
                }
```

to 

```
            foreach ($class->getProperties() as $property) {
                if ((isset($property->info) && $property->info['class'] !== $name) {
                    continue;
                }
```

`$metadata` for my class metadata began to contain data about my child class. Because `$class->getProperties()` reflection function which get properties from parent, that's why property class name and class for which metadata generated is different. 
Maybe I select wrong way or who know how to correct work with yml configuration for class whose properties from parent classes ?

**Comment by goetas** [comment] 2019-10-30 14:45
I guess this is a duplicate of https://github.com/schmittjoh/serializer/issues/1135

**Closed by goetas** 2019-10-30 14:45 UTC
