### ISSUE TITLE
Memory leak in PHP 8.1

### ISSUE THREAD

**Issue by D0L1K** [schmittjoh/JMSSerializerBundle#895] opened 2022-07-22 11:31 UTC
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi, we've switched our Symfony 4.4 project from PHP 7.2 (with JMSSerializerBundle 3.1.0) to PHP 8.1 (with JMSSerializerBundle 4.0.2) where we use long-running commands either with ReactPHP or cron and we've noticed that there is a significant memory usage increase. After some digging we've found out that there is a problem with JMS serializer causing PHP garbage collector not to clean unused stuff.
On 7.2, memory always increased by ~2mb and GC cleared ~2mb afterwards, so it was for example going 20->22->20->22->20mb used. We've found out that with every entity serialized there was a ~6kb increase.
On 8.1 memory always increased by ~10mb and GC cleared ~2mb afterwards, so it was for example going 20->30->28->38->36mb used. With every entity serialized there was a ~12kb increase.

But we've found out that if we don't use DI (singleton to be more precise) and before we want to (de)serialize something we create a new instance of serializer everytime and after (de)serialization we unset $serializer variable, memory is increasing a bit faster, but GC clears everything and we are back at 20->22->20->22->20mb. So we used this as a temporary solution, but it's not a good practice ofc so we would like to switch back to singleton.

I was trying to find any change in PHP which could cause this but was unsuccessful, so can't help you with that.

BtW: we've also tried to switch from JMS to Symfony serializer and GC basically never cleared anything and increase per entity was ~21kb.

## Steps required to reproduce the problem

1. Create more complex entity to serialize
2. Serialize it many times
3. Watch for memory usage before and after every serialization

## Expected Result
* PHP Garbage Collector clears memory as expected after serialization

## Actual Result
* Memory keeps increasing

**Comment by scyzoryck** [comment] 2022-07-26 13:27
Hello! 
Thanks for sharing. I think the issue is also visible in PHPBench test for serializer, but I was unable to locate its issue. I will still look when I will have some time, but if you have any ideas for the cause, feel free to share or create MR with fix! :) 

Best, Marcin

**Comment by scyzoryck** [comment] 2023-02-20 10:36
Hi @D0L1K! 
The fixes for the memory leaks has been merged to master of `jms/serializer`. Could you check `dev-master` version of the package to check if it fixes yours issues? :)

**Closed** 2023-12-12 15:38 UTC
