### ISSUE TITLE
Can't override third party serializer config file

### ISSUE THREAD

**Issue by oatto** [schmittjoh/JMSSerializerBundle#511] opened 2016-03-28 11:04 UTC
I'm using symfony v2.8.4-dev and I have noticed that the overriding file didn't work anymore, because symfony doesn't bring the config key as config name. 

The temporary solution that I have fixed by adding this line in JMS\SerializerBundle\DependencyInjection\Configuration

`->useAttributeAsKey('name')`
next to
`->arrayNode('directories')`
so it becomes:
`->arrayNode('directories')
->useAttributeAsKey('name')`

**Thank you**

**Comment by goetas** [comment] 2017-04-10 13:44
duplicate of https://github.com/schmittjoh/JMSSerializerBundle/pull/531

**Closed by goetas** 2017-04-10 13:44 UTC
