### ISSUE TITLE
What's the purpose of 'id' under 'property_naming' namespace in configuration.

### ISSUE THREAD

**Issue by martinsik** [schmittjoh/JMSSerializerBundle#522] opened 2016-08-02 14:14 UTC
[Configuration.php](https://github.com/schmittjoh/JMSSerializerBundle/blob/master/DependencyInjection/Configuration.php#L81) defines `'id'` option under `property_naming` namespace but it doesn't seem to be used anywhere, it's not even covered in the documentation.

**Comment by monobook** [comment] 2016-09-06 08:57
@schmittjoh

PS: from @weaverryan the [same](https://github.com/schmittjoh/JMSSerializerBundle/issues/449) old issue

**Comment by goetas** [comment] 2017-03-29 09:00
duplicate of https://github.com/schmittjoh/JMSSerializerBundle/issues/449

**Closed by goetas** 2017-03-29 09:00 UTC
