### ISSUE TITLE
Deserialize Embedded

### ISSUE THREAD

**Issue by elvispdosreis** [schmittjoh/JMSSerializerBundle#790] opened 2020-03-19 23:36 UTC
I have an Embedded class, but when deserializing it, I try to select the class
An exception occurred while executing `SELECT ... FROM Promotion t0` Table **database.Promotion** doesn't exist

```
     /**
     * @ORM\Embedded(class="Promotion", columnPrefix=false)
     * @JMS\Type("App\Domain\Promotion")
     * @JMS\Groups ({"list", "details"})
     */
    private $promotion;
```

however it is an Embedded class

**Comment by goetas** [comment] 2020-03-24 07:07
It seems that it tries to load the entity rather than creating a new class.

Are you sure that Promotion is not defined as entity?

**Comment by elvispdosreis** [comment] 2020-03-24 10:47
the problem happens only in those who are using doctrine 2.7.1 or higher I downgraded to 2.7.0 and returned to work

**Comment by goetas** [comment] 2020-03-25 13:35
This is caused by https://github.com/doctrine/orm/pull/8006. I have commented on that PR.

**Comment by goetas** [comment] 2020-04-04 13:30
ive spent some time trying to debug this, but no results so far. can you please share the `Promotion` class code and the other class that is using it as embedded?

**Comment by elvispdosreis** [comment] 2020-04-05 11:46
Yes



[class.zip](https://github.com/schmittjoh/JMSSerializerBundle/files/4433522/class.zip)

**Comment by goetas** [comment] 2020-04-18 04:50
I've tried to reproduce this but again with no luck. Which version of the serializer library are you using?

Can you please send a pull request with a failing test case? https://github.com/schmittjoh/serializer/blob/master/tests/Serializer/Doctrine/ObjectConstructorTest.php is place where you can add your test case

**Comment by elvispdosreis** [comment] 2020-04-20 13:22
"jms/serializer": "^1.14.1"
"doctrine/orm": "2.7.0"

this version of the doctrine works, any version above this error

Em sáb., 18 de abr. de 2020 às 01:50, Asmir Mustafic <
notifications@github.com> escreveu:

**Comment by goetas** [comment] 2020-04-21 06:49
Now I understand. 
`"jms/serializer": "^1.14.1"` is not maintained anymore. The issue that you are reporting the probably has already been fixed in https://github.com/schmittjoh/serializer/pull/1031

**Closed by goetas** 2020-04-21 06:49 UTC
