### ISSUE TITLE
Cache Warmup

### ISSUE THREAD

**Issue by rande** [schmittjoh/JMSSerializerBundle#441] opened 2015-02-17 14:25 UTC
Hello,

Any reason why there is no warmup helper for the serialized metadata ?

This will save some times and solve permissions while deploying symfony application.

**Comment by Bladrak** [comment] 2015-03-19 12:37
@schmittjoh this would be interesting indeed, do you have any feedback on this?

**Comment by gena01** [comment] 2015-06-10 19:35
sounds like a duplicate of #415

**Closed** 2015-06-10 19:41 UTC
