### ISSUE TITLE
Symfony 3 'json' method gives errors with JMS

### ISSUE THREAD

**Issue by askhalil** [schmittjoh/JMSSerializerBundle#523] opened 2016-08-11 07:57 UTC
Thank you for this awesome library. I am running into a weird problem when I call `$this->json($data)` in symfony 3.1 controller. This is the error I am getting is

> Type error: Argument 3 passed to JMS\Serializer\Serializer::serialize() must be an instance of JMS\Serializer\SerializationContext, array given, called in /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php on line 117

jms/serializer-bundle version 1.1
jms/serializer version 1.2

Thank you

**Comment by kubawerlos** [comment] 2016-08-22 09:27
@askhalil to fix this you need to disable short alias ("serializer") for JMS Serializer:

```yaml
# app/config/config.yml

jms_serializer:
    enable_short_alias: false
```

**Comment by yceruto** [comment] 2016-11-23 18:08
@askhalil could close this issue ? @kubawerlos's tip resolves this problem.

**Comment by Tetragramat** [comment] 2017-01-02 16:07
@yceruto I dont think so. If you disable short alias, then \Symfony\Bundle\FrameworkBundle\Controller\Controller::json will not use JMSSerializerBundle, but json_encode or symfony serializer component if enabled. This should be fixed.

**Comment by yceruto** [comment] 2017-01-02 17:32
> If you disable short alias, then \Symfony\Bundle\FrameworkBundle\Controller\Controller::json will not use JMSSerializerBundle.

It is still the expected behavior. Symfony does not use `JMSSerializerBundle` by default, but json_encode or Symfony Serializer Component if enabled (as you said).  

>This should be fixed.

If you need serialize all json response with JMSSerializeBundle, you need then override the `Controller::json()` controller/method in your app. JMSSerializeBundle cannot solve this, simply disable the short alias to avoid conflicts.

**Comment by Tetragramat** [comment] 2017-01-02 17:47
@yceruto Then it should be visible writen in documentation, because it is unexpected behaviour. Everyone will see it as bug.

**Comment by goetas** [comment] 2017-01-03 09:27
as posted by @yceruto [here](https://github.com/schmittjoh/JMSSerializerBundle/issues/523#issuecomment-241359304)

the solution is: 
``` yaml
# app/config/config.yml

jms_serializer:
    enable_short_alias: false
```

**Comment by goetas** [comment] 2017-01-03 09:28
@Tetragramat PR to the documentation are welcome

**Closed by goetas** 2017-01-03 09:27 UTC

**Comment by slince** [comment] 2017-11-02 08:15
@goetas  
Hi ,  the option `enable_short_alias` has been abandoned?

**Comment by goetas** [comment] 2017-11-02 09:13
yes, for the `2.x` versions, the alias is always `jms_serializer` 

(just `serializer` has been  reserved for the symfony serializer)
